### ISSUE TITLE
Include session fetcher in the Xcode project

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client#100]
The session fetcher submodule should be included in the Xcode project. When `GTM_USE_SESSION_FETCHER` is set to `1` the `GTMSessionFetcher` is used instead of the old HTTP fetcher. But the `GTMSessionFetcher` is nowhere included in the Xcode project so even when cloning the gtm-session-fetcher the `GTMSessionFetcher.h` file can't be imported because the file isn't included in the project.

Instead the session fetcher files have to be manually added to the Xcode project, and even worse you have to manually add the `-fobjc-arc` flag to each implementation file.

The session fetcher should be included like the other submodules (OAuth2 and HTTPFetcher).

I'm not sure if pull requests are accepted here but I could open a pull request for this specific issue.

**Comment by thomasvl** [comment]
fyi - we're sorting through this one.  The catch is based on the min os someone wants to support they might need the older fetcher.  Xcode project don't really like dealing with that in a way that lets the project be reusable.  Suggestions for dealing with it welcome.  :)

**Comment by JonasGessner** [comment]
A possible solution could be similar to the way the services, like Analytics or YouTube work. A single Networking header and implementation file. The `Networking.h` imports all the `HTTPFetcher` or `SessionFetcher` headers depending on the value of `GTM_USE_SESSION_FETCHER`. The same thing with `Networking.m` with the implementation files.

The only problem would be that the session fetcher requires ARC and the HTTP fetcher doesn't, but the Networking.m file will always be built with ARC or without, so that probably wouldn't work.

A workaround would be to split the Networking.h and .m apart for the HTTP and session fetcher. One that only includes the session fetcher files, and only when `GTM_USE_SESSION_FETCHER` is 1 and that has ARC enabled. The other that only includes the HTTP fetcher files only when `GTM_USE_SESSION_FETCHER` is 0 and has ARC disabled.

I hope my explanation isn't too bad and you can get what I mean :)

**Comment by JonasGessner** [comment]
I forked the repo and tried to implement it and it seems to work.

There's a major flaw in this project, the OAuth2 project, HTTP fetcher and session fetcher though. The `GTM_USE_SESSION_FETCHER` flag is being set to 1 in all of these projects when the base SDK is iOS 9 or OS X 10.11 which is totally wrong. The session fetcher should be used when the deployment target is iOS 7 or higher. With the current checks, a project built with iOS 8 deployment target and iOS 8 base SDK would be built with the HTTP fetcher, but it should be built with the session fetcher. A project built with the iOS 9 SDK but with a deployment target of iOS 6.0 would be built with the session fetcher, even though the session fetcher is unavailable on iOS 6.

This:
```objc
#if (!TARGET_OS_IPHONE && defined(MAC_OS_X_VERSION_10_11) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_11) \
  || (TARGET_OS_IPHONE && defined(__IPHONE_9_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_9_0)
  #ifndef GTM_USE_SESSION_FETCHER
    #define GTM_USE_SESSION_FETCHER 1
  #endif
#endif
```

should become this:
```objc
#if (!TARGET_OS_IPHONE && defined(MAC_OS_X_VERSION_10_9) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_9) || (TARGET_OS_IPHONE && defined(__IPHONE_7_0) && __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_7_0)

#ifndef GTM_USE_SESSION_FETCHER
#define GTM_USE_SESSION_FETCHER 1
#endif

#endif
```

**Comment by bharat** [comment]
@JonasGessner - I'm trying to get this working as well. I checked out your fork (at `https://github.com/JonasGessner/google-api-objectivec-client`) but it doesn't seem to have any deltas from upstream. Can you make your forked repo public so that I can work off of it while @thomasvl gets the main codebase sorted out? thanks.

**Comment by JonasGessner** [comment]
I've pushed my changes to my fork: https://github.com/JonasGessner/google-api-objectivec-client/commit/da39671fe73e4c3b7a311b8a34976d73996f6207

The session fetcher, OAuth 2 and HTTP fetcher projects need to be updated with the fixed #if statement or it won't work.

I pushed OAuth 2, Session Fetcher and HTTP Fetcher files to my fork of this repo by mistake, but I didn't intent to send a pull request anyway.

**Comment by thomasvl** [comment]
The core project (haven't updated the examples yet), all should be using the SessionFetcher now.
