### ISSUE TITLE
 GTMOAuth2ViewControllerTouch not showing cancel button

### ISSUE THREAD

**Issue by manikkalra** [google/google-api-objectivec-client#101]
I'm presenting GTMOAuth2ViewControllerTouch modally from a view controller and it does not show the cancel button. How do I get the cancel button to show when presenting modally?

Edit: I'm wrapping the GTMOAuth2ViewControllerTouch in a navigation controller and can see the back and forward buttons.

**Comment by Apptation** [comment]
I agree. It's painful that it doesn't have a cancel button

**Comment by Apptation** [comment]
Solution:
For the GTMOAuth2ViewControllerTouch vc created, add a custom button manually:

UIButton *backButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [backButton setFrame:CGRectMake(0, 0, 40, 30)];
    [backButton addTarget:self action:@selector(cancelYouTubeTapped:) forControlEvents:UIControlEventTouchUpInside];
    [backButton setBackgroundImage:[UIImage imageNamed:@"btn-back-normal"] forState:UIControlStateNormal];
    
    UIBarButtonItem *backBarButton = [[UIBarButtonItem alloc] initWithCustomView:backButton];
    [vc.navigationItem setLeftBarButtonItem:backBarButton];

-(void)cancelYouTubeTapped:(id)sender{
    [self.navigationController dismissViewControllerAnimated:YES
                                                  completion:nil];
}

That works perfectly for me.
