### ISSUE TITLE
Request Failed. Unauthorized error message at Sign In screen when user is not logged in

### ISSUE THREAD

**Issue by denistsai** [google/google-api-objectivec-client#102]

**Comment by thomasvl** [comment]
Sorry, we're going to need more info to try and help out. I'm guessing you made a request that require authorization but didn't provide any?  https://github.com/google/google-api-objectivec-client/wiki#authentication-and-authorization has some basic info, and some of the examples (like the Drive one), show setting up an authorizer on the `Service`.
