### ISSUE TITLE
StorageSample: OAuth-2.0-Client-IDs don't fit

### ISSUE THREAD

**Issue by simonmeier** [google/google-api-objectivec-client#107]
I managed to fix the StorageSample but all of the possible OAuth-2.0-Client-IDs keys to be created in the Google Developers Console for the Cloud Storage API, aren't passing the authentication step in the sample. After successfully login in with the client-id, the secret, my google account, the API returns yet another key, which I don't know how to process.

I hope you could provide more information on this or fix the sample in order that we see how to use the storage services. Thanks

**Comment by thomasvl** [comment]
Closing as things should be moving to [GTLR](https://github.com/google/google-api-objectivec-client-for-rest) and believe the samples are working there.
