### ISSUE TITLE
multiple methods named 'initWithArry:' found

### ISSUE THREAD

**Issue by JoeShi** [google/google-api-objectivec-client#108]
OSX: 10.11.1

When i try to build the project, it gives me the error:

```
multiple methods named 'initWithArray:' found
```

in GTMGatherInputStream.m

```
+ (NSInputStream *)streamWithArray:(NSArray *)dataArray {
  return [[[self alloc] initWithArray:dataArray] autorelease];    
}
```

**Comment by thomasvl** [comment]
I don't believe that code is directly in this project.  I think you are talking about one of the fetcher projects instead?

**Comment by JoeShi** [comment]
Yes, I just follow the [Google Calendar API quick start](https://developers.google.com/google-apps/calendar/quickstart/ios?ver=swift) and checkout the source code from 
```
$ svn checkout http://google-api-objectivec-client.googlecode.com/svn/trunk/ google-api-objectivec-client
```
It will automatically fetch two external library. Once it finished, I want to confirm whether everything is OK, so I just double click the GTL.xcodeproj and run the project. It will show me the above error. If I just download the code from Github, it will not compile because of lacking of the fetcher projects. 

One thing I want to confirm with you is whether the code on github is exactly the same as the one I svn checkout from googlecode.com.

Thank you @thomasvl

**Comment by JoeShi** [comment]
@thomasvl  By the way, there are some google SDK distributed by cocoapods, I need use google sign in & google calendar. I got google sign in running with that library. But there is no one with calendar. 

Thus, I try to use the google sign in  & the google-api-objectivec-client together.  What are the minimum file that I have to use from the  google-api-objectivec-client project.

**Comment by katerinafotiou** [comment]
same problem here.

**Comment by thomasvl** [comment]
code.google.com has been retired, we can't update the code there, pull from this github repo to get more up to date sources.

**Comment by thomasvl** [comment]
I'm going to close this off since code.google.com can't be updated and the problem shouldn't be happening with the sources pulled from github.
