### ISSUE TITLE
buildstripheaders deleted all my files

### ISSUE THREAD

**Issue by katerinafotiou** [google/google-api-objectivec-client#112]
I accidentally run this buildstripheaders and IT DELETED ALL MY .H FILES. how can i recover. please help. no backups

**Comment by thomasvl** [comment]
If it was a checked, revert the revert the deletes.  Otherwise, hopefully you have backups, as no one else is likely to have copies of what is on your computer.

**Comment by Igor-Palaguta** [comment]
What this script is doing inside examples? It also removed everything on my machine! Remove it! Your examples can't be compiled. In readme nothing helpful how to compile it. Just one script that breaks everything!
