### ISSUE TITLE
Dependencies are not checked out automatically

### ISSUE THREAD

**Issue by an0** [google/google-api-objectivec-client#117]
[Wiki](https://github.com/google/google-api-objectivec-client/wiki#subsidiary-libraries) is outdated:
> All external libraries needed are checked out automatically with the main API library using Subversion's externals facility.

But since we are now using git instead of Subversion how to checked out external libraries automatically?

**Comment by riannucci** [comment]
I think you can just `git clone --recursive https://github.com/google/google-api-objectivec-client`

**Comment by an0** [comment]
@riannucci thanks. The doc should be updated anyway.

**Comment by riannucci** [comment]
Yeah, it should :D I'm not a member of this project though (just a fellow interested personage) :)

**Comment by thomasvl** [comment]
Did a quick update on the wiki pages, hopefully I got the reference.

fyi - you can actually clone github wikis and send back pull requests for update the docs.
