### ISSUE TITLE
Please update the google drive sample

### ISSUE THREAD

**Issue by liaogang** [google/google-api-objectivec-client#119]
GTLDriveFile have no property downloadURL .

**Comment by ratnesh-iOSdev** [comment]
and to download complete folder as well there is no property present.

**Comment by liaogang** [comment]
I found this will work:

	    GTLDriveFile *file;
	    NSString *s = [NSString stringWithFormat: @"https://www.googleapis.com/drive/v3/files/%@?alt=media",file.identifier];
	    NSMutableURLRequest *r = [NSMutableURLRequest requestWithURL:[NSURL URLWithString: s]];
	    r.HTTPMethod = @"GET";
	    
	    GTMSessionFetcher *f = [self.service.fetcherService fetcherWithRequest: r];
	    [f beginFetchWithCompletionHandler:^(NSData * _Nullable data, NSError * _Nullable error) {}];

**Comment by thomasvl** [comment]
I believe PR #137 included the commits to fix up the sample.

**Comment by arpandesai** [comment]
thanks
