### ISSUE TITLE
Issues with compiling Source Files Directly into iOS Application

### ISSUE THREAD

**Issue by sandeshmirum** [google/google-api-objectivec-client#124]
I am trying to Compiling the Source Files Directly into iOS Application. I followed https://github.com/google/google-api-objectivec-client/wiki/BuildingTheLibrary. But the HTTPFetcher folder is missing. Can you guide me on this?

**Comment by pr0gramm3r8hai** [comment]
SAME HERE ! working on this from ONE WEEK ! still no LUCK !

**Comment by thomasvl** [comment]
Did a quick update to the docs to reference the Deps folder and how things are now pulled via git submodules.
