### ISSUE TITLE
Service Accounts, RS256 JWT encryption, where is that?

### ISSUE THREAD

**Issue by pschuster** [google/google-api-objectivec-client#135]
Hi all,

I just don't get it. Almost giving up! I want my Mac Application to load assets from Google Cloud Storage, no user content involved. And I want the users of my app upload content to Google Cloud Storage, but just with my application. I don't want them to be able to connect outside the app.

As far as I understand this whole topic, I created a service account and assigned the READ and WRITE right using the service accounts email address to the bucket ACLs.

After hours of getting this framework compiled (come on, Google, this should be easier, Parse.com ist a matter of minutes!!) I needed another few hours to notice this code is very incomplete, isn't it?

Reading through these docs (https://developers.google.com/identity/protocols/OAuth2ServiceAccount) I have create a signed JWT which I send to google to receive an access token.

But there is no code to create a JWT and sign it. I tried https://github.com/yourkarma/JWT and modified it. But this library only features HS256 and not RS256. Searching the web for RS256 signing in Objective-C or Swift I did not find anything. Even the jwt.io does not list any Mac/iOS API that works.

I just cannot understand that? This must be easier? Login to the service is the base of everything else, and this is soooooo complicated, no code, old code. 

Please help.
Thanks,
Phillip

**Comment by thomasvl** [comment]
JWT us usually for server to server, which is what it isn't something normally covered here.

@gmrobbins hasn't this come up on the gtm-oauth2 list/project before?  Is there something to point to there?

**Comment by gmrobbins** [comment]
Service accounts are intended for use on a server.

We cannot put account auth credentials securely on a device, so we do not support service accounts on clients. Developers can use a server-based service account, and have the client talk to their server.
