### ISSUE TITLE
Swift Google Drive Api Cancel Sign In

### ISSUE THREAD

**Issue by dailenspencer** [google/google-api-objectivec-client#136]
Hello,

We would like to display a cancel button in a navigation bar above the Google Drive Sign In Web View. The cancel button should dismiss the google sign in process completely. At first, I attempted to simply dismiss the view controller. But this returns "error code 1000". When I looked the GTMOAuth2Sign.m and .h files I noticed there is a function "cancelSigningIn". The "cancelSigningIn" then should call "closeTheWindow" which then performs "webRequestSelector". In the comments it states I need a nil request in order to close the window. Im not sure what that means.  I tired to manually call this from my Nav bar button action but it doesnt work either. Code below. Any help would greatly appreciated. Thanks.

![screenshot 2016-01-09 10 39 56](https://cloud.githubusercontent.com/assets/8779656/12217145/6fc0cb4e-b6bd-11e5-8b6e-e8b0eec36244.png)

**Comment by thomasvl** [comment]
Closing this out as the suggested auth solution is now [GTMAppAuth](https://github.com/google/GTMAppAuth), so this no longer applies.
