### ISSUE TITLE
GTLErrorObject's localizedFailureReason should return localized string

### ISSUE THREAD

**Issue by lorenzhk** [google/google-api-objectivec-client#138]
In GTLErrorObject, instead of simply parenthesized, i would suggest to attempt to localize it as well. Thank you!

NSString *localized = [NSString stringWithFormat:NSLocalizedString(reasonStr, nil)];
    [userInfo setObject:localized
                 forKey:NSLocalizedFailureReasonErrorKey];

**Comment by thomasvl** [comment]
I'm not sure I follow.  Assuming you are talking about:

https://github.com/google/google-api-objectivec-client/blob/master/Source/Objects/GTLErrorObject.m#L49

Then the message can come form the server.  How would you be able to know ever error message a server code generate to then localize it?

It is also possible that some servers might also look at the language headers on the requests and provide localized info already.
