### ISSUE TITLE
Many warnings appear when using GTLNetworking_Sources.m

### ISSUE THREAD

**Issue by yoasha** [google/google-api-objectivec-client#139]
I am using google-api-objectivec-client in my iOS app which makes use of Google Books related API. Instead of using the API as a framework, I am simply dragging the source files into my XCode project and everything works as magic.
Here are the steps I follow to add google api to my project:
1. Drag the following files into XCode project:
- GTLBooks_Sources.m
- GTLOAuth2_Sources
- GTLCommon_Sources.m
- GTLNetworking_Sources.m
2. Disable ARC for GTLCommon_Sources.m and GTLOAuth2_Sources using -fno-objc-arc flag.
3. Set "google-api-objectivec-client" folder in the 'Header Search Paths' project settings as 'recursive'.

And everything is compiling and working great at runtime. The only issue is that I have huge number of warnings of 'Pointer is missing a nullability type specifier'. I am also getting several warnings such as Undeclared selector 'loggedInputStreamForInputStream:'.

When I am removing GTLNetworking_Sources.m file from XCode and instead dragging the individual gtm-session-fetcher files into XCode, then all warnings disappear!

This is not a critical issue of course... however, I love seeing my project clean of warnings. Any idea what I'm doing wrong, and why GTLNetworking_Sources.m is causing these warnings while the other wrapper files don't?

**Comment by thomasvl** [comment]
Clang has some specific rules about the nullability annotations for a single compilation unit.  So when using the _Sources files, it can trigger more warning that don't happen when adding individual files.  Also what warnings trigger seems to change with each Xcode release.  Anyway, we're trying to get them all cleaned up among other work.

**Comment by yoasha** [comment]
Thank you for the prompt reply. 
I am curious to understand why the warnings are specific to GTLNetworking_Sources.m file while there are no warnings with the rest of the _Sources files. There is probably a specific issue with this file, and I suspect it's related to GTMSESSION_BUILD_COMBINED_SOURCES macro, but I'm really not sure about that...
Anyway, thanks a lot for your kind support and for providing this great library!

**Comment by thomasvl** [comment]
The warnings are specific to that file because it is the sources included in there that triggers them.

Anyway, did a bunch of updated to the fetcher the other day (google/gtm-session-fetcher@458cf0c2cc18237541906e3ddacc07a4b1f66ce5).  Hopefully that got them all.

**Comment by yoasha** [comment]
Thank you for your kind support and for trying to help out.

Unfortunately, using the latest source files (downloaded them just now) from all three projects, still results with the same warnings (total of 64 issues. Few of them in GTMSessionFetcher.m file, and the rest in GTMSessionUploadFetcher.m).
Anyway, not a big issue for me.. just thought it worth mentioning. Currently, I workaround this issue by dragging the individual GTMSessionFetcher implementation files into my project, instead of using the GTLNetworking_Sources.m file, in order to avoid the bunch of warnings.

**Comment by thomasvl** [comment]
A while back we made some other changes, as far as we know there aren't any warnings coming from them. If you are still seeing issues, there's a good chance it could be a settings set in your project file; feel free to reopen with the details of what settings are causing it and what the errors are and we can try to help avoid them.
