### ISSUE TITLE
Can't run on device

### ISSUE THREAD

**Issue by derektlo** [google/google-api-objectivec-client#142]
http://stackoverflow.com/questions/35169089/library-load-with-google-calendar-api-obj-c

**Comment by thomasvl** [comment]
Are you packaging it as a framework within the app? i.e. - with the Frameworks directory within the app?  The linker path in the error seem to indicate that is what it is expected.

**Comment by derektlo** [comment]
Hi Thomasvl how do I do that? I can't seem to build the framework? The name is in red. Also, when I try to add to "Show in Finder" it can't find it...because it's not there.

**Comment by derektlo** [comment]
Thomas would you be up for doing a quick Skype screenshare?

**Comment by derektlo** [comment]
Thomas, I ended up (hopefully) fixing the problem by changing GTLiOS Core Mach-O Type from Dynamic Library to Static Library. It now runs on both the simulator and device. Will this have any negative side affects?

**Comment by thomasvl** [comment]
That "works" in the sense that it no longer makes a framework and just bundles all the code into a static library that is then linked it.

I finally got a chance to update the building docs to cover the framework and cocoapods, so I'm going to going to go ahead and close this out, hopefully the update docs can help folks also.
