### ISSUE TITLE
Cannot update files

### ISSUE THREAD

**Issue by kueiapp** [google/google-api-objectivec-client#145]
Always got the error message: {message:“The resource body includes fields which are not directly writable.” code:403 data:[1]}

**Comment by thomasvl** [comment]
Sorry, you are gonna need to provide more info.  Update what files?  Is this a problem checking out?  Is this using some service erroring on your requests.

**Comment by kueiapp** [comment]
Hi there,
some developers also reported it as an issue because of the changes of Google API from v2 to v3.

When updating all files in my Google Drive, it always gave me the error response "The resource body includes fields which are not directly writable." as using Update method in iOS Drive SDK by [Google's tutorial](https://goo.gl/wjpOVV).

--- References ---
[http://stackoverflow.com/questions/34931936/how-to-use-appproperties-in-google-drive-api-v3](http://stackoverflow.com/questions/34931936/how-to-use-appproperties-in-google-drive-api-v3)
[http://stackoverflow.com/questions/35143283/google-drive-api-v3-migration](http://stackoverflow.com/questions/35143283/google-drive-api-v3-migration)

**Comment by thomasvl** [comment]
So you likely need to look at the v3 docs and compare it to your usage to see how things have changed; and make sure you aren't trying to set/change fields that are no longer set able.

As far as more questions about the drive api, you'll want to try the support areas off their docs.  We generate and ship the code for all the apis, but aren't the experts on their apis (or how they are changing with major version releases).

**Comment by AlShevelev** [comment]
I had the same issue and found a solution. The key point is: you must create a new File object without Id and use it in update() method. Here is a piece of my code:
```
val oldMetadata = service!!.files().get(fileId.id).execute()

val newMetadata = File()
newMetadata.name = oldMetadata.name
newMetadata.parents = oldMetadata.parents
newMetadata.description = idHashPair.toDriveString()

val content = ByteArrayContent("application/octet-stream", fileContent)

val result = service!!.files().update(fileId.id, newMetadata, content).execute()

```
It works. I hope it'll help you.
