### ISSUE TITLE
Error 401 Login Required

### ISSUE THREAD

**Issue by anabeatrizacosta** [google/google-api-objectivec-client#147]
Hi!

I 'm new in IOS/SWIFT so I apologize if what I'm asking is silly. (Sorry for my bad English!)

I use the Youtube helper and the objectiveC client library and i follow this tutorial:
[https://nsrover.wordpress.com/2014/04/23/youtube-api-on-ios/]

When trying to upload a video to youtube the following error occurs:

reason: 'unexpected response data (uploading to the wrong URL?)
{"error":{"code":401,"message":"Login Required","data":[{"domain":"global","reason":"required","message":"Login Required","locationType":"header","location":"Authorization"}]},"id":"gtl_1"}'

I don't understand why it says "Login Required", because before the upload I authenticate correctly on the google console and allow to admin my youtube account, i create the proyect in my google developers console and obtain my client ID, and enable de Youtube API.

So, does anyone know why this could be happening? 

Thank you for the help!

**Comment by thomasvl** [comment]
The error is likely telling you that the credentials on the request aren't correct (or are missing).

**Comment by anabeatrizacosta** [comment]
Thanks for your answer Thomas!

I have my OAuth 2.0 credential from Google Developers Console, is that the credential you mean?  

Thanks for advance!

**Comment by gmrobbins** [comment]
The authorizer property of the GTLService object should be set to allow requests to be authorized for the signed-in user.

Use the library's http logging feature to examine the requests and responses to the Google API server. Each request should have an "Authorization" header with a bearer token.
