### ISSUE TITLE
XIBs need to be set to “Build for” “Deployment Target”

### ISSUE THREAD

**Issue by JanX2** [google/google-api-objectivec-client#155]
I could have sent a pull request, but this would be hard to review. So it’s better, if someone internal does this. There might be trust issues otherwise.

This applies particularly to the XIBs used by the projects in Examples and the “GTMOAuth2Window.xib”.

**Comment by thomasvl** [comment]
Closing this out as the suggested auth solution is now [GTMAppAuth](https://github.com/google/GTMAppAuth), so this no longer applies.
