### ISSUE TITLE
Error when build 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in OS X 10.11 - Use NSURLSession (see NSURLSession.h)

### ISSUE THREAD

**Issue by antonydieu** [google/google-api-objectivec-client#158]
google-api-objectivec-client-read-only/Source/HTTPFetcher/GTMHTTPFetcher.m:458:44: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in OS X 10.11 - Use NSURLSession (see NSURLSession.h)

connection_ = [[connectionClass alloc] initWithRequest:request_
delegate:self
startImmediately:NO];

i get an error, but i dont fix it? please help me

**Comment by thomasvl** [comment]
Given the name "google-api-objectivec-client-read-only", are you checking out from svn on code.google.com?  The project has moved here to github.  And it now defaults to using the NSURLSession wrapper.

**Comment by antonydieu** [comment]
I get project google-api-objectivec-client-read-only by : 
 svn checkout http://google-api-objectivec-client.googlecode.com/svn/trunk/ google-api-objectivec-client-read-only

**Comment by thomasvl** [comment]
Yup, that's out of date.  https://github.com/google/google-api-objectivec-client is the current home of the project; so `git clone https://github.com/google/google-api-objectivec-client.git`
