### ISSUE TITLE
InternalDate property not available in pod

### ISSUE THREAD

**Issue by footyapps27** [google/google-api-objectivec-client#164]
I am using the pod available using [https://cocoapods.org/pods/Google-API-Client]. The documentation at Github says that "internalDate" property is present in GTLGMailMessage class. However, the same is not available when trying to access via the pod. 

Any updates as to when the pod will be updated?

**Comment by thomasvl** [comment]
Given that podspec page says _podspec version based on source SVN revision_, I'm guessing it is actually maintained by someone else and based off the now stale svn tree from code.google.com.

https://github.com/google/google-api-objectivec-client/blob/master/GoogleAPIClient.podspec is the current spec.  But note, we're currently working through a framework build issue with it: https://github.com/google/google-api-objectivec-client/issues/162

**Comment by footyapps27** [comment]
When I updated to the pod you mentioned, I was able to the internal date. Thanks.
