### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no result or error in response:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#17]
```
What steps will reproduce the problem?
1.Set deployment target to 4.0.
2.run app in iOS 4.0.
3.

What is the expected output? What do you see instead?
It shouldn't have crashed

What version of the product are you using? On what operating system?
iOS 4.0 Lion

Please provide any additional information below.


```

Original issue reported on code.google.com by `mobilesy...@gmail.com` on 12 Jul 2012 at 9:30

**Comment by thomasvl** [comment]
Since this was originally opened on code.google.com in 2012 and ended up getting some comments about build issues in dependent of the original issue, I'm going to close this out. If someone hits something like this and ends up here, please open a new issue with the details instead.
