### ISSUE TITLE
Dear Google, with great power comes great responsibility. Please update your official tutorial & readme.

### ISSUE THREAD

**Issue by fresh83** [google/google-api-objectivec-client#173]
Guys you are probably costing the world economy $10's if not $100's of thousands of dollars by not updating this tut. How many thousands of developers have gone through your OFFICIAL TUT thinking there is no way GOOGLE would make such big mistakes in their instructions and/or leave a tut as important as this not updated for months" so they tediously go over each step of the tut over and over and over until they want to pull their hair out at a rate of $100 per hour hopefully until they do some research and stumble into this thread.....all bc you guys are too lazy to update your read me?

p.s even if the tut worked its obvious that whoever wrote it has become a victim of their own intelligence, forgetting along the way that just because you understand highly advanced ways of doing things , does not mean it is the best way to teach the public how to do things. It feels very much like the tuts creator wanted to 'wow' us with their deep understanding of X-Code instead of make a no nonsense easy to follow tut anyone from beginners to experts could follow along with without problems in a few mins.

You can also add $7 for a bottle of Excedrin you costed me tonight with your gross incompetence .

**Comment by thomasvl** [comment]
Sorry for the issues, I thought I had made a sweep over everything on this github project, if I missed stuff, please let me know (or even send in pull requests).  As far as issues with docs in other places, odds are those of us that work on the code directly here can't directly update those docs, but again, without pointers to what you are referring too, it is sorta hard to try to help get those things updated also.

**Comment by tomj** [comment]
@fresh83 what are the specific issues with the tutorial?

**Comment by fresh83** [comment]
I dont know where to begin besides to say: https://developers.google.com/google-apps/calendar/quickstart/ios  when followed exactly does not work, the samples in this repo do not work .

**Comment by fresh83** [comment]
I guess we can start with "Why dont the examples work out of the box? "  (as of now we get "GTL/GTLDefines.h not found error) ,  Almost every repo with over 50 stars has examples that just work right out of the box. Get rid of all the fancy jazz(workspaces connected to projects with targets with dependencies and build scripts and on and on)  to impress people and just provide us samples that work ....this is IOS, simplicity is a major guiding principle. Its annoying when developers provide examples that require you to install the pods and thats just one step, but the way this is setup is just uncalled for. 

The important thing to remember in my opinion is that this repo is not just for other Google employees to use, its for everyone. That means everyone from experts to some kid in a 3rd world country trying to build his dream should be able to figure out how to use your API/Lib quickly.

**Comment by jermainehamilton802** [comment]
Jermainehamilton802@gmail.com




On Mon, Apr 4, 2016 at 11:23 PM -0700, "Chuck Kelly" <notifications@github.com> wrote:












I guess we can start with "Why dont the examples work out of the box? "  (as of now we get "GTL/GTLDefines.h not found error) ,  Almost every repo with over 50 stars has examples that just work right out of the box. Get rid of all the fancy jazz(workspaces connected to projects with targets with dependencies and build scripts and on and on)  to impress people and just provide us samples that work ....this is IOS, simplicity is a major guiding principle. Its annoying when developers provide examples that require you to install the pods and thats just one step, but the way this is setup is just uncalled for. 



The important thing to remember in my opinion is that this repo is not just for other Google employees to use, its for everyone. That means everyone from experts to some kid in a 3rd world country trying to build his dream should be able to figure out how to use your API/Lib quickly.

**Comment by tomj** [comment]
@fresh83 you could start by making a PR to fix any glaring issues which you can see in the tutorial.  You could then list the remaining issues and we could work through them as a community.  I agree that this is not the easiest library to pick up and run with, but it's still super useful so let's see what we can come up with.

**Comment by thomasvl** [comment]
@fresh83 I completely missed the bad path on the xib when going through the tutorial, probably because I'm already familiar with the layout of the project, so I just go to where the file is instead.  :(  Anyway, I've filed a few internal bugs for the tutorial to got things fixed up (we don't directly write it).

One minor point, you seem to be assuming everyone responding is a Googler.  I don't believe that's true.  One of the nice things about github is community folks to step up to help improve things.
