### ISSUE TITLE
Not able to run handlers on background operation queue

### ISSUE THREAD

**Issue by brainlessgit** [google/google-api-objectivec-client#175]
According to documentation it should be possible to run handlers on a background operation queue by providing service with a delegate queue:
```
service.delegateQueue = [[NSOperationQueue alloc] init];
```
But it does not work. Handlers are still executed on a main thread.
[Related to this StackOverflow question.](http://stackoverflow.com/questions/36393753/how-yo-use-background-queue-for-google-drive-service-in-objective-c)

**Comment by thomasvl** [comment]
Should be fixed now.  Thanks for the report!
