### ISSUE TITLE
Getting the start time of a GCalEvent

### ISSUE THREAD

**Issue by fresh83** [google/google-api-objectivec-client#176]
Not sure why a NSDate just could not cut it for the folks at google or why this is not working, any ideas? 

```
            for (GTLCalendarEvent *event in events) {
                
                NSLog(@"EVENT:%@",event.summary);
                
                NSDate *startTime=event.start.date.date;
                NSDate *endTime=event.end.date.date;
                NSString *summary=event.summary;
                int START=[startTime timeIntervalSince1970];
                int END =[endTime timeIntervalSince1970];
                int DURATION = END-START;
                NSLog(@"START:%d | END:%d | DURATION:%d",START,END,DURATION);
                [[ModelSingleton sharedInstance] insertNewGCalTask:summary withDurration:DURATION andStrictStartTime:START];
            }
```

**Comment by thomasvl** [comment]
NSDate doesn't work as a straight JSON; and the whole thing with timezones/offsets to the RFC strings gets complex quickly; so another object to wrap up all the state to make sure things are lost can become needed.

Having said that, the Calendar server folks did some _interesting_ things with how they model dates/times which doesn't make it any easier.

You say it isn't working, but you don't really say what isn't working. The built in logging (https://github.com/google/google-api-objectivec-client/wiki#logging-http-server-traffic), should give you a request/response you can include that might provide more detail.

**Comment by fresh83** [comment]
Dude im not at your big bloated company working on unlimited hours from 9-5, shit should just work. Epoch timestamp....universal. Done deal.

**Comment by thomasvl** [comment]
@fresh83 I don't work directly in the calendar space, so I can't comment in full, but from the little I've done in the past, maintaining the timezone is pretty common in calendar contexts.  Apple's Calendar app has support (Prefs -> advanced -> time zone support) to toggle how things act using that info.  You'll also fine it in things like CalDAV standard.  So sure, it may seem like overkill, but fully working the the space ends up saying otherwise.

**Comment by fresh83** [comment]
```
 for (GTLCalendarEvent *event in events) {
                
                NSLog(@"EVENT:%@",event.summary);
                
                NSDate *startTime=event.start.dateTime.date;
                NSDate *endTime=event.end.dateTime.date;
                NSString *summary=event.summary;
                int START=[startTime timeIntervalSince1970];
                int END =[endTime timeIntervalSince1970];
                int DURATION = END-START;
                NSLog(@"START:%d | END:%d | DURATION:%d",START,END,DURATION);
                [[ModelSingleton sharedInstance] insertNewGCalTask:summary withDurration:DURATION andStrictStartTime:START];
            }



```
ended up working, nice, good ol' epoch.
