### ISSUE TITLE
People API Support

### ISSUE THREAD

**Issue by dhandapani-d** [google/google-api-objectivec-client#179]
Hi,

I couldn't find support for Google People API. https://developers.google.com/people/.

IS there any way I can use this library for Google People API. I couldn't find any service classs / GTLObject Subclasses to support Google People API.

**Comment by thomasvl** [comment]
Unfortunately, that the People api is REST only, and this project currently uses JSON-RPC instead; so they won't work at the moment.

But keep an eye out for some news in the near future, we've got some work in flight to support all the newer REST only apis.
