### ISSUE TITLE
Cannot build the ServiceGenerator project. Can't find GTMSessionFetcherService.m

### ISSUE THREAD

**Issue by eliotstock** [google/google-api-objectivec-client#180]
Users of Google Cloud Endpoints need to use the Tools/ServiceGenerator project to generate client code for their APIs. These instructions (which are woefully out of date, but that's another story) talk you through it:

https://cloud.google.com/appengine/docs/java/endpoints/consume_ios

Adapting those instructions to the git repo, I am instead trying:

```
git clone https://github.com/google/google-api-objectivec-client.git
cd google-api-objectivec-client/Source/Tools/ServiceGenerator/
xcodebuild CONFIGURATION_BUILD_DIR=./service-generator-bin
```

Full build output is linked below, but in short, this project depends on GTMSessionFetcher and I've done nothing to pull it in. How should I do that? Your "BuildingTheLibrary" page on the wiki leaves me none the wiser.

[build_output.txt](https://github.com/google/google-api-objectivec-client/files/210084/build_output.txt)

Supposing I want to build the ServiceGenerator using cocoapods. I create a new iOS project in XCode and add a Podfile as follows:

```
pod 'GoogleAPIClient', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
```

Now I run `pod install` and see what I've got. There is no `Source/Tools/ServiceGenerator` directory. So then I have a look at the podspec:

`https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAPIClient/1.0.2/GoogleAPIClient.podspec.json`

There is no subspec for the ServiceGenerator. What am I supposed to do here?

**Comment by thomasvl** [comment]
If you stick `--recursive` in your clone (`git clone --recursive https://github.com/google/google-api-objectivec-client.git`), then you'll also pull the contents of the `Deps` directory and things will build.

Add spec support to build the generator would be fine also, feel free to send out a PR for that.

Most folks having needed to directly use the generator because we provide most of the generated code with the library.

**Comment by thomasvl** [comment]
fyi - I just updated the ServiceGenerator wiki also: https://github.com/google/google-api-objectivec-client/wiki/ServiceGenerator

**Comment by eliotstock** [comment]
Thanks for the quick response. Adding a subspec for the ServiceGenerator seems like the right approach, but I can't see how to submit a PR for it. The spec is of course in a separate repo. This note in that repo suggests bumping the version of the pod and that sounds like something you should be doing, not me:

https://github.com/CocoaPods/Specs/pull/12199

**Comment by thomasvl** [comment]
https://github.com/google/google-api-objectivec-client/blob/master/GoogleAPIClient.podspec is our spec.  Just send in a PR, once we merge it, we'll cut a release so folks can pull via versions, and push the spec back out.

**Comment by eliotstock** [comment]
Done: #181

**Comment by thomasvl** [comment]
@perotinus Any suggestions on if it make sense/how to add the ServiceGenerator so it is easier to get it built for use in a project?  It's a little odd because one doesn't really want the ServiceGenerators sources added to the thing that wants to use it, instead you'd just want to get it built so you could then add your own action to run it and generate some sources.

**Comment by perotinus** [comment]
Hmm. You could add the xcodeproj to the `preserve_paths`, along with a script that runs it and whatever else it needs. I agree that we it's odd to add random things in Podfiles that don't get linked into the product being built.

We could also add the subspec, and a Podfile with a ServiceGenerator target, and a script that pod installs and builds that project. This might cause `pod try` to do funky things though, so we should make sure that that flow works correctly (or fails gracefully).

**Comment by bubenheimer** [comment]
@thomasvl The updated ServiceGenerator wiki is missing the --recursive flag for git which is still critical

**Comment by thomasvl** [comment]
@bubenheimer thanks, updated.
