### ISSUE TITLE
'GTLDefines.h' file not found

### ISSUE THREAD

**Issue by eliotstock** [google/google-api-objectivec-client#182]
Repro steps:

* Start an iOS project with Podfile:

```
platform :ios, '9.3.1'

use_frameworks!

pod 'GoogleAPIClient', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
```

* Write an API for Google Cloud Endpoints and build it to get a discovery file out.

* Clone this repo and build the ServiceGenerator tool from it, then run that tool on the discovery doc to generate Objective-C sources for the client to your cloud endpoints API.

```
CURRENT_DIR=`pwd`
REPO_DIR="google-api-objectivec-client-temp"

# Clone the Google API client library from git. Using --recursive gets the stuff in Deps too.
git clone --recursive https://github.com/google/google-api-objectivec-client.git ${REPO_DIR}

# Build the ServiceGenerator binary
cd ${REPO_DIR}/Source/Tools/ServiceGenerator/
xcodebuild -project ServiceGenerator.xcodeproj -alltargets -configuration Release build

# Run the ServiceGenerator on our discovery doc
cd ${CURRENT_DIR}
${REPO_DIR}/Source/Tools/ServiceGenerator/build/Release/ServiceGenerator ./foo-v1-rpc.discovery --outputDir ./foo-ios-client

# Clean up
rm -rf ${REPO_DIR}
```

* Add `GTLFoo.h` and `GTLFoo_Sources.m` to your project in XCode, where `Foo` is the name of your API.

* In your bridging header file, import your API header:

`#import "GTLFoo.h"`

* Build. You'll get build errors (`Foo` below is now `Api`):

```
/Users/Eliot/dev/biketracker/biketracker-ios/BikeTracker/BikeTracker-Bridging-Header.h:20:9: note: in file included from /Users/Eliot/dev/biketracker/biketracker-ios/BikeTracker/BikeTracker-Bridging-Header.h:20:
#import "GTLApi.h"
        ^
/Users/Eliot/dev/biketracker/biketracker-ios/biketracker-ios-client/GTLApi.h:16:9: note: in file included from /Users/Eliot/dev/biketracker/biketracker-ios/biketracker-ios-client/GTLApi.h:16:
#import "GTLApiConstants.h"
        ^
/Users/Eliot/dev/biketracker/biketracker-ios/biketracker-ios-client/GTLApiConstants.h:21:11: error: 'GTLDefines.h' file not found
  #import "GTLDefines.h"
          ^
<unknown>:0: error: failed to import bridging header '/Users/Eliot/dev/biketracker/biketracker-ios/BikeTracker/BikeTracker-Bridging-Header.h'
```

`GTLDefines.h` is in the Pod, at `Pods/GoogleAPIClient/Source/GTLDefines.h`. Why can't XCode see it?

Build Settings -> Header Search Paths contains `"$(inherited)"`.

**Comment by thomasvl** [comment]
The `GTLApi*` files missing is likely because they aren't on the Header Search Path for your project.  You can likely do the same thing mentioned in https://github.com/google/google-api-objectivec-client/wiki/BuildingTheLibrary#compiling-the-source-files-directly-into-a-mac-or-ios-application, specifically: Add the service's source folder, such as Source/Services/ServiceName/Generated, to the Header Search Path entry of you project's build settings.

Your generated headers not finding the the Core is more interesting.  Since you are using frameworks, the import likely needs to be a framework import. @perotinus how does this work for the services we ship?  We don't seem to be enabled any framework `#import` from for, what would need needed here?

**Comment by thomasvl** [comment]
When you added the `Api`'s to your project, did you do it to and existing target?  Make a new one?  i.e. - what settings did it pick up from the other pods or is it left to all the Xcode defaults.

**Comment by eliotstock** [comment]
XCode can find the header files under my generated code just fine, it's when it compiles them and needs to find the Core stuff that it fails.

Did it to an existing target. Everything is XCode defaults. I've added GTLFoo_Sources.m to the "Compile Sources" phase under the target though.

**Comment by perotinus** [comment]
I think CocoaPods allows sources within the Pod (maybe its subspecs too) to access headers in the Pod with `#include "X.h"` paths. It doesn't propagate that to the depender, though: the depender can access the headers through the 

I think we'd either have to modify the podspec to explicitly add that header search path to the user's project (not all that pretty) or modify the service generator to generate in a "framework mode" where it accesses the headers with `#import <GoogleAPIClient/GTLDefines.h>`.

On that note, it might also be interesting to generate a local podspec for the created files, and tell the user to add that to their Podfile.

**Comment by thomasvl** [comment]
Ok, locally generate API isn't something we've fully sorted through the interactions with CocoaPods then.

@eliotstock Sounds like to get things building you have two options:
1. Add a `Pods/GoogleAPIClient/Headers/Core` to the Header Search Paths in Xcode
1. Tweak the generated files to use `#import <GoogleAPIClient/GTLDefines.h>`.

Yes, neither is great.  We'll look at trying to come up with a better way to handle this.

**Comment by perotinus** [comment]
Apologies, I think that path is wrong! My bad.

I expect that instead you'll need to add:
`<project_dir>/Pods/GoogleAPIClient/Source` and `<project_dir>/Pods/GoogleAPIClient/Source/Utilities`, which contain the actual headers.

**Comment by eliotstock** [comment]
On option 1, the Header Search Paths are, I think, relative to the directory in which the `.xcodeproj` file sits. So in my case I tried:

```
./Pods/GoogleAPIClient/Source
./Pods/GoogleAPIClient/Source/Utilities
```

And also:

```
$SRCROOT/Pods/GoogleAPIClient/Source
$SRCROOT/Pods/GoogleAPIClient/Source/Utilities
```

I still get the same build error.

On option 2, which source files in the generated code need this hack? There are imports in every header for one of:
```

GTLDefines.h
GTLObject.h
GTLQuery.h
GTLService.h
```

Are you saying I need to edit every header file and change this sort of thing:

```
#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif
```

to this?

`#import <GoogleAPIClient/GTLObject.h>`

**Comment by thomasvl** [comment]
Re edit the header, yes.  That's what I was thinking might work.

There's gotta be a Header Search Path trick that also works…wait, try User Header Search Path also?  There's another Xcode setting that toggle if the user and system path are checked independently.

I haven't gotten a chance to try to recreate this locally, so I'm somewhat stuck trying to guess what the layout is.  :(

**Comment by eliotstock** [comment]
Got it. You forgot:

`./Pods/GoogleAPIClient/Source/Objects`

If I add that to Header Search Paths or User Header Search Paths, my main target builds. My *Test target still fails to build, but I think I can sort that out.

The approach @perotinus mentioned where you'd modify the service generator to generate in a "framework mode" sounds pretty good to me. Can we leave this open till you've had a crack at that?

**Comment by thomasvl** [comment]
Yup, please keep it open.  We're kicking around idea, nothing pretty at the moment.  :(

**Comment by perotinus** [comment]
I dug into this a bit more, and it appears that it only happens with the Swift bridging header. Importing the header in Objective-C code works fine.

I think this has to do with header maps. When I disable header maps, the Objective-C import fails as well. When I disable header maps in the pod project, the GoogleAPIClient pod fails to build, because it can't find its own headers. Perhaps the bridging header doesn't use the header map, and so it fails to build? It looks like the bridging header gets access to its project's (target's?) header map, while the Objective-C code gets access to the header maps for everything.

I'm not quite sure why this is so. It seems like the header map magic breaks in this particular case, but they're much too magical for me to understand whether this is something we can fix. We might end up having to go with one of the ugly solutions, adding more preprocessor defines and checks as needed to make this case work. I can't think of a clean solution here right now (though it's Friday evening, so that may not be a surprise),

**Comment by perotinus** [comment]
OK, I haven't thought of any cleaner solutions. I think we're stuck between:
* suggest the Header Search Paths modification
* add a "framework mode" to the service generation tool

@thomasvl, do you think this case is worth adding a framework mode to the tool? I don't think this will affect Objective-C users, just Swift users generating their own services.

**Comment by thomasvl** [comment]
Hm, if it is Swift only, does that mean we can't make the Pod auto define things to use the namespaced import?  i.e. - would that break for the ObjC developer?

**Comment by anuragedushire** [comment]
@thomasvl Are you planning to add --gtlrFrameworkName flag in RPC as well?

**Comment by thomasvl** [comment]
I wasn't planning on it since per the note on the main README.md, folks really should be moving to REST based library instead of this one.

**Comment by anuragedushire** [comment]
Sorry, I missed that note.

**Comment by anuragedushire** [comment]
By the way the pod mentioned with the flag is 'GoogleApiClient', I guess it would better be 'GoogleApiClientForRest'

**Comment by thomasvl** [comment]
Oops, thanks.

**Comment by atrepeklis** [comment]
What worked for me was to add to the User Header Search Path `Pods` and select recursively.
