### ISSUE TITLE
OAuth2 files missing from source sub folder

### ISSUE THREAD

**Issue by jweinst1** [google/google-api-objectivec-client#183]
So I am trying to follow this sample project set up

https://developers.google.com/google-apps/calendar/quickstart/ios?ver=swift#step_4_prepare_the_project

When I get to the part where the OAuth2 xib file is needed to be added to the project's supporting files, it's not present in the source folder, either on here or in the cloned repo.

`google-api-objectivec-client/Source/OAuth2/Touch/GTMOAuth2ViewTouch.xib`

Is there a better way to get the above file? Or group of files.

**Comment by thomasvl** [comment]
This has been mentioned a few times in issues and on the Google Group.  That quickstart isn't something we can directly update. :(

The path you likely want is `google-api-objectivec-client/Deps/gtm-oauth2/Source/Touch/GTMOAuth2ViewTouch.xib`.

**Comment by thomasvl** [comment]
I'll keep this open so hopefully folks can find it more easily.
