### ISSUE TITLE
service.retryEnabled=YES neither service.retrySelector=@selector(ticket:willRetry:forError:) is not working

### ISSUE THREAD

**Issue by brainlessgit** [google/google-api-objectivec-client#184]
The issue is described in this stackoverflow [question](http://stackoverflow.com/questions/36589510/how-to-use-automatic-retry-in-google-drive-fetcher-services-in-objective-c)

In a few words: automatic retry is not working. Requests with errors like (403, 500) are not retried. 
Selector to specify where retry or not also is not executed.

Code snipped to reproduce the issue:
```Objective-C
- (void) reproduceTheIssue: (GTMOAuth2Authentication *) authorizer {

    GTLServiceDrive * driveService = [[GTLServiceDrive alloc] init];
    driveService.retryEnabled = YES;
    driveService.authorizer = authorizer;
    //    driveService.fetcherService.retryEnabled = YES; //this also doesn't help
    //    driveService.retrySelector =  @selector(ticket:willRetry:forError:);
    const int DELAY = 0;
    const int NUMBER_OF_FOLDERS = 50;

    for (int i = 0; i < NUMBER_OF_FOLDERS; i++) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, DELAY * NSEC_PER_SEC), dispatch_get_main_queue(), ^{

            GTLDriveFile * nestedFolder = [GTLDriveFile object];
            NSString * folderName = [NSString stringWithFormat: @"folder-number-%i", i];
            nestedFolder.name = folderName;
            nestedFolder.mimeType = @"application/vnd.google-apps.folder";
            nestedFolder.parents = @[@"appDataFolder"];

            GTLQueryDrive * query = [GTLQueryDrive queryForFilesCreateWithObject: nestedFolder uploadParameters: nil];
            [driveService executeQuery: query completionHandler: ^(GTLServiceTicket * ticket, GTLDriveFile * updatedFile, NSError * error) {
                if (error == nil) {
                    NSLog(@"Successfully created a folder %@", updatedFile);
                } else {
                    NSLog(@"Failed to a folder: %@ error: %@", folderName, error);
                }
            }];
        });
    }
}

- (BOOL) ticket: (GTLServiceTicket *) ticket willRetry: (BOOL) suggestedWillRetry forError: (NSError *) error {
    NSLog(@"I will never be called :( with this arguments ticket: %@, willRetry: %i, error :%@", ticket, suggestedWillRetry, error);
    return YES;
}
```

**Comment by thomasvl** [comment]
Looks like you are mixing selectors and blocks.  The retry selector is for use when you use the executeQuery:delegate:didFinishSelector: (that way you provide the delegate to invoke the selector on).  Since you are using executeQuery:completionHandler:, try using the retryBlock property instead.

**Comment by brainlessgit** [comment]
@thomasvl, thank you for response. RetryBlock really makes sense. But I have tried it and it didn;t work also.
```Objectve-C
    driveService.retryBlock =
            ^BOOL (GTLServiceTicket * ticket,
                    BOOL suggestedWillRetry,
                    NSError * error) {
                NSLog(@"Retry block. Error: %@", error);
                return YES;
            };
```
It was never executed and ` Error Domain=com.google.GTLJSONRPCErrorDomain Code=500 "(Internal Error)" UserInfo={error=Internal Error, NSLocalizedFailureReason=(Internal Error)` were not retried.

**Comment by gmrobbins** [comment]
In the GTL library, the retry block/selector unfortunately is less often useful than it implies. 

The retry logic is in the http fetcher class, so the retries only reflect errors that show up during network requests. Due to the GTL library using JSON-RPC requests, most server errors are returned with a 200 http status, so the fetcher thinks no retry is needed.

You can verify that the retry support does work by forcing a networking error. Here's an example of doing that:
```
driveService.rpcURL = [NSURL URLWithString:@"https://www.googleapis.com/bad-rpc"];
driveService.retryBlock = ^(GTLServiceTicket *ticket, BOOL suggestedWillRetry, NSError *error){
  return suggestedWillRetry;  // Set a breakpoint here.
};
[driveService executeQuery:...
```
General error handling on GTL queries should be done by the app in the completion handler. Errors for which the server could return a 200 status usually reflect programmer or data error and thus are rarely automatically retriable, anyway.

**Comment by brainlessgit** [comment]
@gmrobbins thank you.
