### ISSUE TITLE
tvos

### ISSUE THREAD

**Issue by vodkhang** [google/google-api-objectivec-client#186]
Hi all,

Have anyone try to integrate google api objective-C client into a tvos app. I want to make a simple app that needs to access data from youtube. If I used the latest version of the library, it gave me error of GTMSessionFetcher not found. If I used an older version, it reported that it could not find the UIWebView.

If anyone can post a tutorial or some instruction about this issue, I would really appreciate

**Comment by thomasvl** [comment]
There's some pull requests in flight to add things to the current cocoapods.  So I think some folks have looked at it.

**Comment by thomasvl** [comment]
We landed pull request to the pod with tvos support, but I can't say I've personally tried it, if things aren't working, can you provide more details about what is failing?

**Comment by vodkhang** [comment]
Hi Thomas,

Thanks for your info, I will try it out. Do you know if we can play youtube video on tvos yet?

**Comment by thomasvl** [comment]
> Do you know if we can play youtube video on tvos yet?

Can't say I've done much myself on tvOS, so I don't really know.  I'd be sorta surprised if there wasn't a way to play video steams on tvOS.  :)
