### ISSUE TITLE
OCR flag removed from GTLQueryDrive

### ISSUE THREAD

**Issue by bvirlet** [google/google-api-objectivec-client#192]
Hello,

The following commit removed the ability to request OCR when uploading a file to Google Drive:
https://github.com/google/google-api-objectivec-client/commit/b4aefbaf9798bfe5c299bdf7399fcdca8296efd9#diff-ffb88e41e2b01e483814280f806fd51cL81

It's also suspicious because the ocrLanguage flag has been kept.

How should we use this feature now?

Thanks!

**Comment by thomasvl** [comment]
You'll want to check the drive api docs, but doing a quick peek at https://developers.google.com/drive/v3/web/migration#methods, it mentions:

> OCR is enabled automatically for image imports

So it looks like the bit is gone, but the language is still there for helping improve things.

**Comment by bvirlet** [comment]
Thanks for the update. For the record: it's indeed automatically done and the users can now do right click -> open with Google Docs to see the text version of their PDF or image document.
