### ISSUE TITLE
Google Calendar API in swift return recurrence = nil while return recurringEventId

### ISSUE THREAD

**Issue by EmanRezk** [google/google-api-objectivec-client#194]
When queryForEventsListWithCalendarId it return all events but repeated task return recurrence = nil and recurringEventId = id how to get recurrence rule to know if this event repeated daily, weekly or monthly

**Comment by thomasvl** [comment]
I'm not very familiar with the calendar api (the library supports a bunch of apis, so we don't always know the ins and out of all of them).

Looking at the [docs](https://developers.google.com/google-apps/calendar/v3/reference/events/list#http-request), there is the `showDeleted` and `showSingle` parameters that will cause the recurring events to be expanded out, you didn't mention if you were passing anything for those.  Are you setting either of those?

The docs also list [stackoverflow for support for their api](https://stackoverflow.com/questions/tagged/google-calendar), so posting your question there is more likely to be seen by some of the calendar server team.

When posting questions (here or on stackoverflow), including the [http logs](https://github.com/google/google-api-objectivec-client/wiki#logging-http-server-traffic) can help as it shows exactly what the client is sending and the server is replying with.

**Comment by EmanRezk** [comment]
Thanks for your reply but  i set singleEvents = true and events return but recurrence return nil

**Comment by thomasvl** [comment]
As I read those linked docs, you want singleEvents = false.  By setting it to true you are telling the server to expand the recurring event, setting it to false would seem to tell it to send the recurrence info hung off the initial event instead.

**Comment by EmanRezk** [comment]
When read docs i set singleEvent = false to get recurrence events but i get Error:The operation couldn’t be completed. (The requested ordering is not available for the particular query.) and the query not worked until set singleEvent = true in this case all events returned.

**Comment by EmanRezk** [comment]
Finally i reached to the answer after trying all queries i found to get events with recurrence mode "Daily - Weekly - Monthly" i should use the following query

`let query = GTLQueryCalendar.queryForEventsListWithCalendarId("primary")`
