### ISSUE TITLE
[iOS] Gmail API cannot delete email 

### ISSUE THREAD

**Issue by raymond00000** [google/google-api-objectivec-client#197]
Hi,

I can delete user email in Android Gmail API. 

This is my code under iOS:            

 private let scopes = [ kGTLAuthScopeGmail, kGTLAuthScopeGmailCompose ,kGTLAuthScopeGmailModify]

let query = GTLQueryGmail.queryForUsersMessagesDelete();
            query.messageId = I;
             service.executeQuery(query, completionHandler: nil)

I know when user (me) clicks accepts OUTH2 permission, the permission message says the app won't be allowed to delete email, but I can do so in Android, also, there is GTLQueryGmail.queryForUsersMessagesDelete() in objC library, so I believe it should be possible to delete email? But the above code does not work. 

Many thanks for confirming the real case.

**Comment by thomasvl** [comment]
What is the error?  What scopes do you requesting when you do your OAuth2 flow?

**Comment by raymond00000** [comment]
Thanks for reply.
my bad, it should be

query.identifier = I;

Many thanks.
