### ISSUE TITLE
Error installing Google-API-Client

### ISSUE THREAD

**Issue by riksof-arqam** [google/google-api-objectivec-client#199]
` Error installing Google-API-Client
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force http://google-api-objectivec-client.googlecode.com/svn/trunk/ -r 393 /var/folders/5r/hwgpm3nx77z5lb7gdvwggwl80000gn/T/d20160623-18560-1jwl7e7

svn: E160013: Unable to connect to a repository at URL 'http://google-api-objectivec-client.googlecode.com/svn/trunk'
svn: E160013: 'http://google-api-objectivec-client.googlecode.com/svn/trunk' path not found`

![screen shot 2016-06-23 at 4 21 37 pm](https://cloud.githubusercontent.com/assets/12997375/16301418/c37fd27e-395e-11e6-9dc3-b41d4bab9b60.png)

**Comment by thomasvl** [comment]
_Google-API-Client_ isn't the official pod we control.  The pod provided by this project is: [GoogleAPIClient](https://github.com/google/google-api-objectivec-client/blob/master/GoogleAPIClient.podspec)

Use the official pod, or contact the authors of the other pod to correct their pod.

**Comment by riksof-arqam** [comment]
This solved my problem. Thank you Thomas Van Lenten.

On Thu, Jun 23, 2016 at 5:26 PM, Thomas Van Lenten <notifications@github.com
