### ISSUE TITLE
The documentation should be rewritten completely! 

### ISSUE THREAD

**Issue by zboralski** [google/google-api-objectivec-client#201]
Using my endpoints from a polymer app was a breeze... 

Using my endpoints from iOS is a complete nightmare. ... We just wasted 3 hours trying to make it work.

> Open google-api-objectivec-client/Source/GTL.xcodeproj and expand GTLSource and Common.
> Select all the files in the subgroups, excluding the OAuth 2.0/Mac group.

Tried that... I just get errors.. The above instructions are not clear.

I tried using a podfile... then adding my generated files... nothing works.

This is a joke.

**Comment by thomasvl** [comment]
Just so I'm clear, which docs are you talking about, something on the wiki here or docs some place else?

Are these custom endpoints?  You might find some info in https://github.com/google/google-api-objectivec-client/issues/182 of use.  The change recently landed, but I haven't had a chance to cycle make to the wiki to better document it.

As noted in the README for this repo, for new project we suggest you use https://github.com/google/google-api-objectivec-client-for-rest instead as it has moved to REST allowing it to support more features.
