### ISSUE TITLE
With GTL_USE_SESSION_FETCHER enabled, build fails

### ISSUE THREAD

**Issue by JanX2** [google/google-api-objectivec-client#206]
When building the current head (a641db12e662bdf281a45a173caf525d35602284) with GTL_USE_SESSION_FETCHER enabled, build fails here:
https://github.com/google/google-api-objectivec-client/blob/666baa2e88f0ed5e5b31e4d5ea6a6facbaeda096/Source/Objects/GTLService.m#L715

The error is the following:

    …google-api-objectivec-client/Source/Objects/GTLService.m:715:14: Instance method '-setRequestValue:forHTTPHeaderField:' not found (return type defaults to 'id')

**Comment by thomasvl** [comment]
Are you building with pods or manual pulls?  If it is manual pulls, then odds are your pull of the gtm-session-fetcher needs to be updated to match the current code.  If it was with pods, then you caught a mistake on my part, I was pushing pod updates yesterday, but went out of order on a one dep, and hadn't pushed the pod for this library yet.  I just did the push now, so updating based on pods should be working again.

**Comment by thomasvl** [comment]
Closing this since I believe it is fixed with the rest of the podspec pushes.

**Comment by JanX2** [comment]
I am using manual pulls. Apparently I did not update “gam-session-fetcher”. Thanks!
