### ISSUE TITLE
Fetching extremely large YouTube playlists

### ISSUE THREAD

**Issue by JanX2** [google/google-api-objectivec-client#207]
When fetching extremely large YouTube playlists (thousands of entries), is there a better way than to increase the default value for `kMaxNumberOfNextPagesFetched` in the following line?

https://github.com/google/google-api-objectivec-client/blob/666baa2e88f0ed5e5b31e4d5ea6a6facbaeda096/Source/Objects/GTLService.m#L57

An example playlist would be this one:
https://www.youtube.com/playlist?list=PLMNj_r5bccUyXJLUDRykf9sX3Yc_vHBQD

**Comment by thomasvl** [comment]
A lot of this is going to depend on the app/ux you are building.  For example, it likely doesn't make sense to fetch the whole thing before displaying anything.  So it might make sense to not follow next pages, and instead fetch them one chunk at a time and fetch the next chunk as the user scrolls in the list.  You'd do this by setting the `pageToken` on the query with the value from the `nextPageToken` on the last result.

Assuming you are using [list](https://developers.google.com/youtube/v3/docs/playlists/list), it has a `maxResults` parameter, so you can increase that so you are fetching more at a time, cutting down the number of pages needed.

But for really long lists, it still might make sense to manually fetch the pages yourself along with increasing the max results per page.

**Comment by JanX2** [comment]
This is an experimental CLI app. It’s mainly for dumping the current channel metadata. 

`maxResults` already is at 50, but at a default limit of 25 pages that only amounts to 1250 entries and thus is not enough to fetch all entries of the playlist above.

**Comment by thomasvl** [comment]
Yup, you'll need to manually kick off the next set of pages yourself by using the last nextPageToken.
