### ISSUE TITLE
GTMOAuth2ViewCOntrollerTouch.h file not found 

### ISSUE THREAD

**Issue by dailenspencer** [google/google-api-objectivec-client#208]
Hello there, I have googled a good bit for the answer to this question but cant find much. I transferred my project to a new machine and now im getting this error. Screen shot below : 
![screen shot 2016-08-10 at 9 30 37 am](https://cloud.githubusercontent.com/assets/8779656/17562033/b5f249bc-5edd-11e6-8a38-c3c5ffc91102.png)

**Comment by thomasvl** [comment]
How do you have the code checked out?  pods or directly?  If pods, what pods?

**Comment by dailenspencer** [comment]
Directly. I assume the fact that the project cant find GTL.xcodeproj has something to do with it. I just havent touched this project in a while so once I transferred it I realized im a bit clueless as to whats going on.

**Comment by thomasvl** [comment]
Yea, in that case, you hadn't touched it in a very long time.  The GTL project is gone and we have the GTLCore one.  It doesn't expose a static lib any more either, does have a Framework target.   You'll likely want to start with the [BuildingTheLibrary wiki page](https://github.com/google/google-api-objectivec-client/wiki/BuildingTheLibrary) to reconstruct things.

As mentioned on the docs, we've released a newer project to replace this one [GTLR](https://github.com/google/google-api-objectivec-client-for-rest).  It is an more modern version that also moves from JSON-RPC to JSON/REST to support more google services.  There's a migration doc on that wiki also to help coach though some of the api changes when moving.

**Comment by dailenspencer** [comment]
Okay awesome thats exactly what im looking for. Thank you
