### ISSUE TITLE
Would this work to access the Google Core Reporting Api?

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client#209]
Hi, The documentation isn't clear.  Would this work to access the Google analytics core reporting api?

**Comment by thomasvl** [comment]
You want the newer version of the library [google-api-objectivec-client-for-rest](https://github.com/google/google-api-objectivec-client-for-rest).  Specifically, https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/AnalyticsReporting/GTLRAnalyticsReporting.h#L4-L9 seems like what you are after.
