### ISSUE TITLE
Error:invalid_Client The  OAuth client was not found 

### ISSUE THREAD

**Issue by Ehsanwww** [google/google-api-objectivec-client#211]
Hi  everyone, I used an open source project about Email_Client which is based on  google API(Gmail API,GTL Core),when I want to run the project(Actually it was written for  IOS )  google page comes to screen and  this Error comes out "Error:invalid_Client The  OAuth client was not found ".

Can anyone help me to  solve this problem ??

Thanks in advance

**Comment by thomasvl** [comment]
Sorry, I'm not sure what the _Email_Client_ project is.  You might be better off asking on that projects issues/discussion.  My guess is the app needs a client id, so some request is getting set without having given it a client id.  We have a little info about getting ids for our examples on the [wiki](https://github.com/google/google-api-objectivec-client/wiki#example-applications).

**Comment by Ehsanwww** [comment]
Thanks for your reply, the picture below is  error i got 
![screen shot 1395-06-12 at 10 17 49 p m](https://cloud.githubusercontent.com/assets/20922281/18215157/1105c22c-7165-11e6-869c-7c759aa9d67d.png)

**Comment by thomasvl** [comment]
Sorry, without more info about what the app is doing, I really don't know what is happening.

**Comment by Ehsanwww** [comment]
That problem solved,in order to use Google API I  must sign  in this website [console.developers.google.com]  and get  a valid Client ID.

**Comment by lightlinksolution** [comment]
I set both correct GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET but still, it does not work.

**Comment by yashuvishnalia** [comment]
@lightlinksolution 
1. try reset keys
2. check if the values passed in setting.py file is in '' like 'somevalue'

i faced the same problem where i put the value with ' '(string format) in heroku. when i removed the ''.
run the command again _heroku config:set GOOGLE_KEY=akdjshfkaalskdf_
it worked

**Comment by PatelAshish1** [comment]
That error is displayed in case that under “APIs & auth” -> “Consent screen” you have empty field “PRODUCT NAME” – you need to select e-mail address as well.

You can find “Consent screen” under a link!, click on project name and then go to “APIs & auth” -> “Consent screen”

Find Full Source Code At [Here](https://icetutor.com/question/error-invalid_client-no-application-name/)

**Comment by joandylevi** [comment]
That error is displayed in case that under “APIs & auth” -> “Consent screen” you have empty field “PRODUCT NAME” – you need to select e-mail address as well.

You can find “Consent screen” under a link!, click on project name and then go to “APIs & auth” -> “Consent screen”

Full Source Available At [Here](https://icetutor.com/question/error-invalid_client-no-application-name/)

**Comment by ganthimathigit** [comment]
s,dcx sx

**Comment by borisjavier** [comment]
Where do I find GOOGLE_CLIENT_ID?

**Comment by SmartManoj** [comment]
@borisjavier https://console.developers.google.com/apis/credentials/oauthclient/

**Comment by GauravDeepak** [comment]
This might be the problem with the url you have provided when creating the client id and secret key,
Because google block if you try to access is from unlisted url.
and for sure check your credential once again.....
For Example http://websitename.com

**Comment by datdinhquoc** [comment]
faced the same error, but my case was funny, copied the URL from terminal but it had newline characters coz the URL was too long

**Comment by thaonv-0510** [comment]
> faced the same error, but my case was funny, copied the URL from terminal but it had newline characters coz the URL was too long

lol same
