### ISSUE TITLE
APi Documentation currently pointing to old SVN hosting

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client#216]
The Google Search console API documentation is currently pointing at the old deleted SVN hosting

https://developers.google.com/webmaster-tools/v3/libraries
- Select Obj c

`<p>Get the latest <a href="http://code.google.com/p/google-api-objectivec-client/source/browse/#svn%2Ftrunk%2FSource%2FServices">Google Search Console API client library for Objective-C</a>.</p>`

Suggest this be updated to here!

**Comment by thomasvl** [comment]
Thanks, I've filed a bug with the team in questions since I can't updated it myself.

**Comment by grantkemp** [comment]
Thanks!
