### ISSUE TITLE
I getting Error In Generate API using discovery file...

### ISSUE THREAD

**Issue by balkrishanyadav** [google/google-api-objectivec-client#222]
Hello, I am using google discovery end point framework. I am generation file for iOS using discovery file and getting below error with no sucess...

Balkrishans-iMac:~ balkrishanyadav$ /Users/balkrishanyadav/Desktop/GTL/google-api-objectivec-client-for-rest/Source/Tools/ServiceGenerator/build/Release/ServiceGenerator /Users/balkrishanyadav/Desktop/Output/smartmovie-v1.discovery   --outputDir ~/Users/balkrishanyadav/Desktop/Output
Generation Settings:
  Output Directory: ~/Users/balkrishanyadav/Desktop/Output
  Discovery Root URL: https://www.googleapis.com/
  Flags:
   + Use service name directory: NO
   + Remove unknown files: NO
   + Allow rootURL overrides: YES
Loading API File(s):
 + Fetching ~/Desktop/Output/smartmovie-v1.discovery
ERROR: The api description doesn't appear to be a discovery REST description
ERROR: There were one or more errors; check the full output for details.

Thanks,

**Comment by thomasvl** [comment]
Sounds like your file '/Users/balkrishanyadav/Desktop/Output/smartmovie-v1.discovery' is not a REST discovery document.  Without knowing what is looks like it is sorta hard to help trouble shoot.  How did you make that file?
