### ISSUE TITLE
Cocoapod cannot resolve sub specs - PeopleService

### ISSUE THREAD

**Issue by sonnykr** [google/google-api-objectivec-client#224]
[!] Unable to satisfy the following requirements:

- `GoogleAPIClientForREST/PeopleService (= 1.3.0)` required by `Podfile`

Specs satisfying the `GoogleAPIClientForREST/PeopleService (= 1.3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by thomasvl** [comment]
I believe you meant to open this issue on the follow up project: [google-api-objectivec-client-for-rest](https://github.com/google/google-api-objectivec-client-for-rest), it has replaced this one.

As far as that error, I believe it means you are trying to have your min os version set to something lower than what the 1.3.0 release supported.  That podspec contains:

```ruby
  s.ios.deployment_target = '7.0'
  s.osx.deployment_target = '10.9'
  s.tvos.deployment_target = '9.0'
```

You didn't mention what you were trying to support.
