### ISSUE TITLE
google drive Api Uploadprogressblock not work

### ISSUE THREAD

**Issue by csenazmulbubt** [google/google-api-objectivec-client#228]
self.service.executeQuery(query, completionHandler: { (ticket, file, error) in
            onCompleted?((file as? GTLRDrive_File)?.identifier, error)
        })
        self.service.uploadProgressBlock = { (ticket,byte1,byte2) in
            
        }

**Comment by thomasvl** [comment]
There isn't much to go on here, but it would seem you are setting the progressBlock after starting the query.  The the progressBlock is copied from the query when it is start, so try setting it before you start the query.

**Comment by csenazmulbubt** [comment]
Thank you so much @Thomas Van Lenten ..problem solved ..Google drive api its possible to add Downloadprogressblock but downloadProgress block not present or block in this api
