### ISSUE TITLE
Unable to link to the IOS static library following instructions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#55]
```
What steps will reproduce the problem?

1. svn checkout http://google-api-objectivec-client.googlecode.com/svn/trunk/ 
google-api-objectivec-client-read-only
2. ignore issue #40 ;)
3. open google-api-objectivec-client-read-only/Source/GTL.xcodeproj/, i.e. 
launch Xcode
4. select GTL in project navigator view; this will show the project (GTL) and 
its targets (esp. GTLTouchStaticLib; marked in red) in the left column of the 
standard editor view
5. New | Project: Empty Application; Product Name: Test
6. There are now two projects open inside Xcode: GTL and Test
7a. Attempt dragging target GTLTouchStaticLib from GTL.xcodeproj’s standard 
editor view to Test.xcodeproj’s Link Binary With Libraries list (under Build 
Settings for target Test in standard editor view)
7b. Alternatively, drag libGTLTocuhStaticLib.a from GTL.xcodeproj’s project 
navigator view (under GTL | Products) into Test.xcodeproj’s Link Binary With 
Libraries list; build target Test

What is the expected output? What do you see instead?

7a. Apparently the target as such cannot be dragged into Link Binary With 
Libraries list.
7b. This leads to an error at compile time:

Apple mach-O Linker Error
ld: library not found for -lGTLTouchStaticLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Hence neither a verbatim (“The static library target should be dragged into 
your application project's Build Phases 'Link Binary with Libraries' list”) 
nor a more liberal interpretation of the build instructions [1] seems to work.

What version of the product are you using? On what operating system?

* latest code base from svn; Xcode 5.0.2, OS X 10.9

Please provide any additional information below.

see also issues #53 (and #40)

```

Original issue reported on code.google.com by `tiptopl...@gmail.com` on 27 Dec 2013 at 4:25

**Comment by jigs611989** [comment]
I have the same problem. 

Did you manage to fix the 
problem?

Ld /Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Products/Debug-iphonesimulator/BrilliantBurger.app/BrilliantBurger normal x86_64
    cd /Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode7.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Products/Debug-iphonesimulator -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleAppUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleAuthUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleInterchangeUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleNetworkingUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleParsingUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GooglePlusUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleSignIn/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleSymbolUtilities/Libraries -L/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GoogleUtilities/Libraries -F/Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Products/Debug-iphonesimulator -F/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/AppInvites/Frameworks -F/Users/jignesh/Desktop/BrilliantBurger/BrilliantBurger/Pods/GPPCore/Frameworks -filelist /Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Intermediates/BrilliantBurger.build/Debug-iphonesimulator/BrilliantBurger.build/Objects-normal/x86_64/BrilliantBurger.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lAFNetworking -lBolts -lFBSDKCoreKit -lFBSDKLoginKit -lFBSDKShareKit -lGIDExShared -lGSDK_Overload -lGTLCore -lGTLPlusV1Private -lGTMOAuth2_external -lGTMOAuth2_internal -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lOpenInChrome -lProtocolBuffers -lSignIn -lz -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreText -framework GINInvite -framework GPPCore -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -fobjc-arc -fobjc-link-runtime -framework MessageUI -framework Accounts -framework Social -framework CoreTelephony -framework CoreLocation -framework MapKit -lsqlite3 -lPods -Xlinker -dependency_info -Xlinker /Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Intermediates/BrilliantBurger.build/Debug-iphonesimulator/BrilliantBurger.build/Objects-normal/x86_64/BrilliantBurger_dependency_info.dat -o /Users/jignesh/Library/Developer/Xcode/DerivedData/BrilliantBurger-dfdfrpsrswmphvavfwruyyvvtssc/Build/Products/Debug-iphonesimulator/BrilliantBurger.app/BrilliantBurger

ld: library not found for -lGIDExShared
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by thomasvl** [comment]
jigs611989 - your problem seems to be "GIDExShared", which isn't part of this project.

**Comment by jigs611989** [comment]
Hi thomasvl,

you are right. I have post a comment at wrong place but i have the same issue. i am not talking about this project. In my project i have added pod 'GoogleSignIn', '2.2'. Everything work fine. but after uploading to my svn server then checkout the project from svn i got same error as above.

**Comment by jose920405** [comment]
@jigs611989

i have exactly the same problem.. You found any solution?

**Comment by thomasvl** [comment]
Closing out.  There is an official podspec for this project now, and should be working for folks.  Make sure you are using the one that matches the one checked in to this project on github.
