### ISSUE TITLE
google-api-objectivec-client + gtm-http-fetcher Duplicate interface definition for class GTMHTTPUploadFetcher

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#83]
```

1. Add google-api-objectivec-client and gtm-http-fetcher in one project as 
frameworks
2. Try to build


What is the expected output? What do you see instead?

error in GTLService.m:86

// If the upload fetcher class is available, it can be used for chunked uploads
//
// We locally declare some methods of the upload fetcher so we
// do not need to import the header, as some projects may not have it available
@interface GTLUploadFetcherClass : GTMBridgeFetcher

Error: Duplicate interface definition for class GTMHTTPUploadFetcher

This is because after preprocess it has

@interface GTMHTTPUploadFetcher : GTMHTTPFetcher in GTMHTTPUploadFetcher.h:45 

and

@interface GTMHTTPUploadFetcher : GTMHTTPFetcher in GTLService.m:86

To forward declare interface and some methods it should just implement some 
private category like this:

@interface GTLUploadFetcherClass  (somePrivateCatogory) in GTLService.m:86
...

Anyway it should be imported (as module) in .m to allow compiler to see forward 
declaration

So require to use 

#if GTL_USE_SESSION_FETCHER
#import "GTMSessionUploadFetcher.h"
#else
#import "GTMHTTPUploadFetcher.h"
#endif

instead of 

// If the upload fetcher class is available, it can be used for chunked uploads
//
// We locally declare some methods of the upload fetcher so we
// do not need to import the header, as some projects may not have it available
@interface GTLUploadFetcherClass : GTMBridgeFetcher
...


```

Original issue reported on code.google.com by `serg.f...@gmail.com` on 4 Mar 2015 at 2:34

Attachments:
- [Screen Shot 2015-03-04 at 17.14.07.png](https://storage.googleapis.com/google-code-attachments/google-api-objectivec-client/issue-83/comment-0/Screen Shot 2015-03-04 at 17.14.07.png)

**Comment by digiacomo** [comment]
I'm sorry to report it still doesn't work. My old friend "Duplicate interface definition" is always there.

**Comment by kalvish21** [comment]
I'm seeing the same error. And I had the exact line in my Podfile as mentioned above.

**Comment by aytek** [comment]
Still getting same error in a cocoapod swift project.

//in pod file
pod 'Google-API-Client/Drive', '~> 1.0'

//bridge file
#import "GTMOAuth2ViewControllerTouch.h"
#import "GTLDrive.h"

//error
.../Pods/Google-API-Client/Source/Objects/GTLService.m:86:1: Duplicate interface definition for class 'GTMHTTPUploadFetcher'

**Comment by Isuru-Nanayakkara** [comment]
I only get the error when I use the `use_frameworks!` flag in the `Podfile`. I opened a [question](http://stackoverflow.com/q/33581805/1077789) on StackOverflow with more details.

**Comment by srinathp90** [comment]
Simple sollution here..

Go to edit scheme -> Select Build -> Build option untick the Parallelize Build

Now run your App
