### ISSUE TITLE
github GLT project not buildable

### ISSUE THREAD

**Issue by FilippDuhov** [google/google-api-objectivec-client#91]
When i am cloning repo with svn(http://google-api-objectivec-client.googlecode.com/svn/trunk) every sing if fine, but when i am cloning this git repo, some folders are not available - HTTPFetcher, JSON, Networking, etc., so project isn't buildable.

**Comment by thomasvl** [comment]
Yup, we were using svn:externals before to auto download things.  We are still finishing doing the setup here, so that's one part that hasn't been fully replaced as git submodules aren't a complete replacement for it.

**Comment by eliotstock** [comment]
Uh, this project doesn't even build anymore because of this! You need to fix this!

**Comment by eliotstock** [comment]
@FilippDuhov Try this in the meantime. I was able to get this to build by going through all the external dependencies and manually 'git clone'ing them into project and alongside it like this:

    git clone https://github.com/google/google-api-objectivec-client.git google-api-objectivec-client-temp

    # svn propget svn:externals .
    # HTTPFetcher http://gtm-http-fetcher.googlecode.com/svn/trunk/Source
    # OAuth2 http://gtm-oauth2.googlecode.com/svn/trunk/Source
    # JSON https://github.com/stig/json-framework.git/tags/v2.3.2/Classes

    git clone https://github.com/google/gtm-http-fetcher.git google-api-objectivec-client-temp/Source/HTTPFetcher
    git clone https://github.com/google/gtm-oauth2.git google-api-objectivec-client-temp/Source/OAuth2
    git clone https://github.com/stig/json-framework.git -b v2.3 google-api-objectivec-client-temp/Source/JSON

    # We also need the GTM session fetcher project at the top level to work around issue https://github.com/google/google-api-objectivec-client/issues/88
    git clone https://github.com/google/gtm-session-fetcher.git gtm_session_fetcher

I was able to build at least the 'ServiceGenerator' binary from this, but haven't tried building the whole project.

    cd google-api-objectivec-client-temp/Source/Tools/ServiceGenerator/
    xcodebuild CONFIGURATION_BUILD_DIR=../../../service-generator-bin

**Comment by thomasvl** [comment]
Yup, git doesn't have anything that works as nice/smoothly as svn:external did, there are options, but they all have trade offs, so we're trying to figure out what will end up being easiest for folks.

**Comment by FilippDuhov** [comment]
submodules should resolve your problems, and ours too ;)

**Comment by thomasvl** [comment]
Yea, that is one of the options.  I haven't used them before, and looking at the docs, it seems like it requires everyone cloning the repo has to know about the submodules and do extra work to pull them.

**Comment by FilippDuhov** [comment]
No, git will automatically clone all submodules with cloning repo. Git contains each submodule commit id, so when you update submodule it will be in repo commit changes, and checkout automatically with checkout original git.

**Comment by thomasvl** [comment]
Hm, that doesn't match how I was reading https://git-scm.com/book/en/v2/Git-Tools-Submodules#Cloning-a-Project-with-Submodules.  Those docs seemed to imply they would be empty directories that you have to manually init/update unless you know to add --recursive to the initial clone.

**Comment by FilippDuhov** [comment]
Sorry for my mistake, i am rarely use command line git, thins i am talking about doing SourceTree app for me.

**Comment by yzhong52** [comment]
@thomasvl I think submodule is a good way to do. Yes, we need to do git init/update manually. But for those who are using TortoiseGIT or SourceTree, it will be easier. But no matter what, it is better than let it in this unbuildable stage.

**Comment by thomasvl** [comment]
Quesiton: do folks using TortoiseGIT or SourceTree tend not to use/want CocoaPods?

**Comment by FilippDuhov** [comment]
You can easy use CocoaPods with SourceTree, but it isn't rly nice work on build server (in my case, build server creates builds after each commit), script that will update your submodules is much more easier to do, imho.

**Comment by thomasvl** [comment]
Yea, we've been debating adding pods and adding a script for the folks that don't want pods that could checkout the dependencies (since submodules don't checkout by default for anyone using command lines)

**Comment by thomasvl** [comment]
Submodules added so things should be building now on a checkout.  There are a few other issues open for getting cocoapods going also.
