### ISSUE TITLE
GTLYouTubeVideo instantiated instead of GTLYouTubeResourceId

### ISSUE THREAD

**Issue by fumoboy007** [google/google-api-objectivec-client#92]
My understanding is that Objective-C objects are instantiated based on the JSON object’s `kind` attribute. The `GTLYouTubeResourceId` does not have its own `kind` value; instead its `kind` value is one of `youtube#video`, `youtube#channel`, or `youtube#playlist`.

So when `GTLObject` comes across one of these `GTLYouTubeResourceId` JSON objects with the `kind` attribute set to `youtube#video`, then a `GTLYouTubeVideo` object is instantiated. The properties of this object are still set correctly as if it were a `GTLYouTubeResourceId`, but the class is wrong. I am not sure if this is problematic in Objective-C, but it gives me an error in Swift when I try to access `videoId`: `-[GTLYouTubeVideo videoId]: unrecognized selector sent to instance`.

I think the cleanest solution would be to change the API such that `GTLYouTubeResourceId` JSON objects have their own `kind` attribute value and then move the type of resource (e.g. `youtube#video`) to a new attribute called something like `resourceKind`.

**Comment by gmrobbins** [comment]
Unfortunately, this is a longstanding problem (see #63). There is a bug open at Google against the YouTube API for this (10691692).

For now, apps should just directly access the JSON of that incorrect class instance rather than the properties.

**Comment by thomasvl** [comment]
Should be fixed now.

**Comment by fumoboy007** [comment]
Thanks!
