### ISSUE TITLE
Build fails right after checkout on dependency GTMSessionFetcher.m

### ISSUE THREAD

**Issue by fruxo-** [google/google-api-objectivec-client#93]
Hi, I do need to be able to build an iOS client form an AppEngine Endpoints discovery document and for that I have followed the instruction given here: https://cloud.google.com/appengine/docs/java/endpoints/consume_ios#Java_Compiling_the_client_library_generator_and_generating_your_library

Sadly the code-base does not build, which is a big blocker for me, and the following error is produced:

```
/Users/aUser/aFolder/Projects/aProject/ios/gtm_session_fetcher/Source/GTMSessionFetcher.m:3017:48: Conflicting parameter types in implementation of ‘getCookiesForTask:completionHandler:’: ‘void (^ _Nonnull __strong)(NSArray<NSHTTPCookie *> * _Nullable __strong)’ vs 'void (^__strong _Nonnull)(NSArray *__strong)'
```

Could you please:
1. correct me in case I am doing something wrong
2. otherwise provide me with either a fix or a viable workaround?

Thanks!

*Steps to reproduce the issue*
- OSX 10.10.5
- Xcode Version 7.0 beta 4 (7A165t)
- ```svn checkout http://google-api-objectivec-client.googlecode.com/svn/trunk/  google-api-objectivec-client-read-only```
- open ```google-api-objectivec-client-read-only/Source/Tools/ServiceGenerator/ServiceGenerator.xcodeproj``` in Xcode
- build (```command + B```)
- the error is reproduced

**Comment by fruxo-** [comment]
Update.

The build also fails with Xcode Version 6.4 (6E35b)

Is this library still a viable option for generating iOS clients from GAE CloudEndpoints?

Thanks

**Comment by eliotstock** [comment]
It's true that this has become a bit of a mess. Not sure how you even managed to the the GTM Session Fetcher project down. I was able to get this to build by going through all the external dependencies and manually 'git clone'ing them into project and alongside it like this:

    git clone https://github.com/google/google-api-objectivec-client.git google-api-objectivec-client-temp

    # svn propget svn:externals .
    # HTTPFetcher http://gtm-http-fetcher.googlecode.com/svn/trunk/Source
    # OAuth2 http://gtm-oauth2.googlecode.com/svn/trunk/Source
    # JSON https://github.com/stig/json-framework.git/tags/v2.3.2/Classes

    git clone https://github.com/google/gtm-http-fetcher.git google-api-objectivec-client-temp/Source/HTTPFetcher
    git clone https://github.com/google/gtm-oauth2.git google-api-objectivec-client-temp/Source/OAuth2
    git clone https://github.com/stig/json-framework.git -b v2.3 google-api-objectivec-client-temp/Source/JSON

    # We also need the GTM session fetcher project at the top level to work around issue https://github.com/google/google-api-objectivec-client/issues/88
    git clone https://github.com/google/gtm-session-fetcher.git gtm_session_fetcher

I was able to build at least the 'ServiceGenerator' binary from this, but haven't tried building the whole project.

    cd google-api-objectivec-client-temp/Source/Tools/ServiceGenerator/
    xcodebuild CONFIGURATION_BUILD_DIR=${CURRENT_DIR}/service-generator-bin

See how you get on with that.

**Comment by tidbeck** [comment]
I managed to build using this steps:
 
* Checkout `google-api-objectivec-client` and `gtm-session-fetcher` (notice the renaming of the folder)

> git clone https://github.com/google/google-api-objectivec-client.git
> git clone https://github.com/google/gtm-session-fetcher.git gtm_session_fetcher

* Patch `GTMSessionFetcher.m`

```objective-c
--- a/Source/GTMSessionFetcher.m
+++ b/Source/GTMSessionFetcher.m
@@ -3014,7 +3014,7 @@ static NSMutableDictionary *gSystemCompletionHandlers = nil;
}
    
 - (void)getCookiesForTask:(NSURLSessionTask *)task
-        completionHandler:(void (^)(NSArray *))completionHandler {
+        completionHandler:(void (^)(NSArray<NSHTTPCookie *> *))completionHandler {
   if (completionHandler) {
     NSURLRequest *currentRequest = task.currentRequest;
     NSArray *cookies = [self cookiesForURL:currentRequest.URL];
```

* Set `OS X Deployment Target` to `OS X 10.10` (as I use Xcode 7 but still run Yosemite on my machine)

**Comment by dennis910130** [comment]
Thanks @tidbeck !

**Comment by lferro9000** [comment]
Why not just add the modules as submodules and correct the project paths?

**Comment by thomasvl** [comment]
Submodules added, so that should fix the build issues for folks.
