### ISSUE TITLE
no result or error in response

### ISSUE THREAD

**Issue by jose920405** [google/google-api-objectivec-client#94]
In my GTLService File.. The 1145 Line is

GTL_DEBUG_ASSERT(errorJSON != nil, @"no result or error in response:\n%@",
jsonWrapper);

I have the same Problem

*** Assertion failure in -GTLService parseObjectFromDataOfFetcher:, 
/xxx/xxxx/Documents/git-repos/dev-objectivec/xxx/ios-app/Pods/iOS-GTLYouTube/Obj
ects/GTLService.m:1145

https://github.com/brynbellomy/iOS-GTLYouTube/issues/4

**Comment by thomasvl** [comment]
Without the request/response, it is sorta hard to guess what might be happening.  Try turning on logging (https://github.com/google/google-api-objectivec-client/wiki#logging-http-server-traffic) to get more details.

**Comment by thomasvl** [comment]
The issue you reference seems to be a fork of 3 year old code, can you get logs with something more current?
