### ISSUE TITLE
How to get list of projects from Google Storage ( Nearline ) 

### ISSUE THREAD

**Issue by James24** [google/google-api-objectivec-client#95]
I able to list out buckets from particular project. I have many projects in my cloud storage. I cant able to remember all the name, so i want to list out my projects and by selecting particular project, i have to list out its buckets. 

 GTLQueryStorage *query = [GTLQueryStorage queryForBucketsListWithProject:@"myproject"];

the above code list out buckets of specified project only.. is there anyway to list out all the projects ?

**Comment by thomasvl** [comment]
Sorry for the delay in replying.  While we generate the sources for all the services supported, we aren't the experts on all of them.  I'd suggest using the support areas linked off the the Storage api's docs: https://cloud.google.com/storage/docs/resources-support
