### ISSUE TITLE
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

### ISSUE THREAD

**Issue by eliotstock** [google/google-api-objectivec-client#97]
Please implement App Transport Security (https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html) to stop these errors showing up on iOS 9.0 and later.

**Comment by gmrobbins** [comment]
There's nothing for the library to implement; it's just up to the servers to support App Transport Security cert requirements, and I think Google's servers now do so. We're successfully using the GTL library via GTMSessionFetcher with ATS enabled on iOS 9.

Can you provide the http log for a request and response failing due to ATS?

**Comment by eliotstock** [comment]
Oh, I see. Didn't realise this would be a server side change. I see https://<my_app_id>.appspot.com is using TLS 1.2. If there's nothing for the library to do, I don't see what's causing the error.

You can get a log of all network operations by doing this in your AppDelegate's application:didFinishLaunchingWithOptions: method. Below is snippet of mine, but it's not that helpful.

Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:1] 23:32:36.683 {
	LoaderWhatToDo
	    Request: <CFURL 0x14e669a0 [0x396c13e8]>{string = https://bike-tracker.appspot.com/_ah/api/rpc?prettyPrint=false, encoding = 134217984, base = (null)}
	CachePolicy: 1
	   WhatToDo: originload
	CreateToNow: 0.04802s
	} [3:1]
Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:2] 23:32:36.808 {
	AddCookies Continue: request POST https://bike-tracker.appspot.com/_ah/api/rpc?prettyPrint=false HTTP/1.1
	       HTTPProtocol: Task: 16dc6e20
	} [3:2]
Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:3] 23:32:36.810 {
	Protocol Enqueue: request POST https://bike-tracker.appspot.com/_ah/api/rpc?prettyPrint=false HTTP/1.1
	         Request: <CFURLRequest 0x16f500a0 [0x396c13e8]> {url = https://bike-tracker.appspot.com/_ah/api/rpc?prettyPrint=false, cs = 0x0}
	         Message: POST https://bike-tracker.appspot.com/_ah/api/rpc?prettyPrint=false HTTP/1.1
	         Sending: dict [7] {
	                      Accept-Language: en-gb
	                        Cache-Control: no-cache
	                      Accept-Encoding: gzip, deflate
	                         Content-Type: application/json-rpc; charset=utf-8
	                           User-Agent: cc.biketracker.BikeTracker/1.0 google-api-objc-client/2.0 iPhone/9.0 hw/iPhone5_4 (gzip)
	                               Accept: application/json-rpc
	                  }
	} [3:3]
Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:4] 23:32:36.811 {
	SocketStream IO Logging
	} [3:4]
Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:5] 23:32:36.814 {
	TCP Connection Created
	conn: 0x16f58c50 for name bike-tracker.appspot.com, port 443
	} [3:5]
Sep 21 23:32:36  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:6] 23:32:36.815 {
	TCP Connection Start
	conn: 0x16f58c50
	} [3:6]
Sep 21 23:32:37  BikeTracker[229] <Notice>: CFNetwork Diagnostics [3:7] 23:32:37.564 {
	SocketStream TCP Connection Complete
	 conn: 0x16f58c50
	   fd: 17
	error: 0
	} [3:7]
